wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1735046588.876217
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 15
      - 23
      4: 3.6.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
